### ISSUE TITLE
Desktop integration of appimage from Github repo error

### ISSUE THREAD

**Issue by naveenjohnsonv** [srevinsaju/zap#1]
Tried to install https://github.com/kapitainsky/RcloneBrowser from zap, downloaded and installed correctly but desktop integration failed.

```
100% Downloaded https://github.com/kapitainsky/RcloneBrowser/releases/download/1.8.0/rclone-browser-1.8.0-a0b66c6-linux-x86_64.AppImage from kapitainsky
Configuring...
Integrating with desktop...
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 373, in __init__
OSError: libpcre.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "zap/cli.py", line 232, in install_gh
  File "zap/zap.py", line 360, in install
  File "zap/libappimage/libappimage.py", line 31, in __init__
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/tmp/.mount_zap-x88hwZaH/usr/local/lib/libappimage.so'. Most probably this dynlib/dll was not found when the application was frozen.
[631963] Failed to execute script test

```

**Comment by srevinsaju** [comment]
@naveenjohnsonv which linux distro are you running zap on?

**Comment by naveenjohnsonv** [comment]
> @naveenjohnsonv which linux distro are you running zap on?

Pop!_OS 20.04

**Comment by srevinsaju** [comment]
Is it an apt based distro?

**Comment by srevinsaju** [comment]
```bash
sudo apt install libpcre3```

**Comment by naveenjohnsonv** [comment]
> Is it an apt based distro?

Yes ofc it's based on Ubuntu 20.04 LTS

**Comment by srevinsaju** [comment]
@naveenjohnsonv how did you install zap?

**Comment by naveenjohnsonv** [comment]
With your install script from terminal

**Comment by srevinsaju** [comment]
Ok, found the bug!. Thanks for reporting. I will push a fix quickly!! Will attribute you in the release for finding the bug :tada:

**Comment by srevinsaju** [comment]
@naveenjohnsonv Can you reinstall zap using the same command you installed zap with? I fixed the bug and its working for me. Can you test the new build? Thanks!

**Comment by naveenjohnsonv** [comment]
Yes it's fixed now. Great work!

**Comment by srevinsaju** [comment]
Let me know if there are any other bugs too! So I can push a beta release. You are #1 :smile:

**Comment by naveenjohnsonv** [comment]
So far so good. I'll test a little more extensively what I can. Happy I could help you with this. It's very useful.

**Comment by srevinsaju** [comment]
Great!
