### ISSUE TITLE
Github install fails with ImHex

### ISSUE THREAD

**Issue by eadmaster** [srevinsaju/zap#70]
````
$ zap install --github --from WerWolv/ImHex

? Choose a release v1.16.2
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/srevinsaju/zap/index.GitHubSurveyUserReleases(0x7ffda5e74b40, 0x5, 0x7ffda5e74b40, 0x5, 0x7ffda5e74b38, 0xd, 0x1, 0x2, 0xc00016a1e1, 0x2b, ...)
        /home/runner/work/zap/zap/index/github.go:82 +0xc7c
github.com/srevinsaju/zap/appimage.Install(0x7ffda5e74b40, 0x5, 0x7ffda5e74b40, 0x5, 0x7ffda5e74b38, 0xd, 0x1, 0x2, 0xc00016a1e1, 0x2b, ...)
        /home/runner/work/zap/zap/appimage/utils.go:70 +0x1e3e
main.installAppImageCliContextWrapper(0xc0000c70c0, 0x7, 0xc)
        /home/runner/work/zap/zap/cli.go:46 +0x278
github.com/urfave/cli/v2.(*Command).Run(0xc0000d8c60, 0xc0000c6d40, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc00009f520, 0xb2cc60, 0xc0000b4070, 0xc0000bc000, 0x5, 0x5, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/zap/zap/main.go:157 +0xdfd
````

**Comment by srevinsaju** [comment]
@eadmaster looks like the release has a zipped AppImage. https://github.com/WerWolv/ImHex/releases They should actually release the unzipped AppImage
